<a href="https://colab.research.google.com/github/Shreya-Reddy-7/AI-Powered-Intelligent-Recruitment-Candidate-Analytics-System/blob/main/Resume_Parsing_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#DATASET

In [5]:
from google.colab import files
uploaded = files.upload()

Saving Resume.csv to Resume.csv

#PYTHON LIBARIES

In [7]:
!pip install spacy scikit-learn nltk
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 67.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [34]:
import pandas as pd
import re
import json
import spacy
import nltk

from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [35]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [36]:
nlp = spacy.load("en_core_web_sm")

# Load Resume Dataset (Extract Raw Text)

In [37]:
df = pd.read_csv("/content/Resume.csv")

df = df[['Resume_str']]   # only resume text
df.head()

                                          Resume_str
0           HR ADMINISTRATOR/MARKETING ASSOCIATE\...
1           HR SPECIALIST, US HR OPERATIONS      ...
2           HR DIRECTOR       Summary      Over 2...
3           HR SPECIALIST       Summary    Dedica...
4           HR MANAGER         Skill Highlights  ...

#DATA CLEANING

In [38]:
def clean_text(text):

    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^A-Za-z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)

    return text.lower()

df['cleaned_resume'] = df['Resume_str'].apply(clean_text)

df.head()

,Resume_str,cleaned_resume
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,hr administrator marketing associate hr admin...
1,"HR SPECIALIST, US HR OPERATIONS ...",hr specialist us hr operations summary versat...
2,HR DIRECTOR Summary Over 2...,hr director summary over years experience in ...
3,HR SPECIALIST Summary Dedica...,hr specialist summary dedicated driven and dy...
4,HR MANAGER Skill Highlights ...,hr manager skill highlights hr skills hr depa...

#Text Preprocessing (Tokenization, Stopword Removal, Lemmatization)

In [39]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [40]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):

    tokens = word_tokenize(text)

    tokens = [word for word in tokens if word not in stop_words]

    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

df['processed_resume'] = df['cleaned_resume'].apply(preprocess_text)

In [41]:
df.head()

,Resume_str,cleaned_resume,processed_resume
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,hr administrator marketing associate hr admin...,hr administrator marketing associate hr admini...
1,"HR SPECIALIST, US HR OPERATIONS ...",hr specialist us hr operations summary versat...,hr specialist u hr operation summary versatile...
2,HR DIRECTOR Summary Over 2...,hr director summary over years experience in ...,hr director summary year experience recruiting...
3,HR SPECIALIST Summary Dedica...,hr specialist summary dedicated driven and dy...,hr specialist summary dedicated driven dynamic...
4,HR MANAGER Skill Highlights ...,hr manager skill highlights hr skills hr depa...,hr manager skill highlight hr skill hr departm...

#Extract Skills using TF-IDF

In [42]:
skills_list = [
'python','java','c++','sql','machine learning','deep learning','nlp',
'data analysis','data science','excel','power bi','tableau',
'html','css','javascript','react','node','flask','django',
'tensorflow','pytorch','scikit learn'
]

In [43]:
def extract_skills(text):

    skills_found = []

    for skill in skills_list:
        if skill in text:
            skills_found.append(skill)

    return list(set(skills_found))

In [44]:
df['skills'] = df['processed_resume'].apply(extract_skills)

#Extract Years of Experience and Education

In [45]:
def total_experience(text):

    text = text.lower()

    pattern = r'(\d+)\+?\s*(years|year|yrs|yr)'

    matches = re.findall(pattern, text)

    years = [int(match[0]) for match in matches]

    if years:
        return max(years)
    else:
        return 0

In [46]:
df['total_experience'] = df['Resume_str'].apply(total_experience)

In [47]:
education_keywords = [
'bachelor','bachelor of technology','b.tech','b.e',
'master','m.tech','mca','mba',
'bsc','msc','phd',
'computer science','information technology',
'electronics','mechanical engineering'
]

In [48]:
def extract_education(text):

    education_found = []

    for edu in education_keywords:
        if edu in text:
            education_found.append(edu)

    return list(set(education_found))

In [49]:
df['skills'] = df['skills'].apply(lambda x: x if x else ["Not Mentioned"])

In [50]:
df['education'] = df['cleaned_resume'].apply(extract_education)

In [51]:
df.head()

,Resume_str,cleaned_resume,processed_resume,skills,total_experience,education
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,hr administrator marketing associate hr admin...,hr administrator marketing associate hr admini...,[data analysis],15,[]
1,"HR SPECIALIST, US HR OPERATIONS ...",hr specialist us hr operations summary versat...,hr specialist u hr operation summary versatile...,[Not Mentioned],0,"[bachelor, master]"
2,HR DIRECTOR Summary Over 2...,hr director summary over years experience in ...,hr director summary year experience recruiting...,[excel],20,"[bachelor, mba, master]"
3,HR SPECIALIST Summary Dedica...,hr specialist summary dedicated driven and dy...,hr specialist summary dedicated driven dynamic...,[excel],20,[]
4,HR MANAGER Skill Highlights ...,hr manager skill highlights hr skills hr depa...,hr manager skill highlight hr skill hr departm...,[excel],0,[bachelor]

In [52]:
df.isnull().sum()#null values

Resume_str          0
cleaned_resume      0
processed_resume    0
skills              0
total_experience    0
education           0
dtype: int64

#Convert to JSON

In [53]:
import json

resume_json = []

for index,row in df.iterrows():

    data = {
        "resume_id": index + 1,
        "skills": row['skills'],
        "education": row['education'],
        "experience_years": row['total_experience']
    }

    resume_json.append(data)

json_output = json.dumps(resume_json, indent=4)

print(json_output)

[
    {
        "resume_id": 1,
        "skills": [
            "data analysis"
        ],
        "education": [],
        "experience_years": 15
    },
    {
        "resume_id": 2,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 3,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "mba",
            "master"
        ],
        "experience_years": 20
    },
    {
        "resume_id": 4,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 20
    },
    {
        "resume_id": 5,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 6,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 7,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 8,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 9,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 15
    },
    {
        "resume_id": 10,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "electronics"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 11,
        "skills": [
            "Not Mentioned"
        ],
        "education": [],
        "experience_years": 3
    },
    {
        "resume_id": 12,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 13,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 14,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 15,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 16,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 17,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 18,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 19,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 20,
        "skills": [
            "data analysis"
        ],
        "education": [
            "bachelor",
            "mba",
            "master"
        ],
        "experience_years": 7
    },
    {
        "resume_id": 21,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 22,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 3
    },
    {
        "resume_id": 23,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 9
    },
    {
        "resume_id": 24,
        "skills": [
            "excel"
        ],
        "education": [
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 25,
        "skills": [
            "Not Mentioned"
        ],
        "education": [],
        "experience_years": 11
    },
    {
        "resume_id": 26,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 27,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 28,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 3
    },
    {
        "resume_id": 29,
        "skills": [
            "excel"
        ],
        "education": [
            "master"
        ],
        "experience_years": 20
    },
    {
        "resume_id": 30,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 31,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 32,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 9
    },
    {
        "resume_id": 33,
        "skills": [
            "excel"
        ],
        "education": [
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 34,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 25
    },
    {
        "resume_id": 35,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 36,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 37,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 38,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 39,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 30
    },
    {
        "resume_id": 40,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "information technology"
        ],
        "experience_years": 10
    },
    {
        "resume_id": 41,
        "skills": [
            "excel"
        ],
        "education": [
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 42,
        "skills": [
            "sql",
            "java"
        ],
        "education": [
            "mba",
            "computer science"
        ],
        "experience_years": 1
    },
    {
        "resume_id": 43,
        "skills": [
            "excel"
        ],
        "education": [
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 44,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 45,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 46,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 47,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 30
    },
    {
        "resume_id": 48,
        "skills": [
            "data analysis",
            "excel"
        ],
        "education": [
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 49,
        "skills": [
            "data analysis"
        ],
        "education": [
            "bachelor",
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 50,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "mba",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 51,
        "skills": [
            "excel"
        ],
        "education": [
            "master"
        ],
        "experience_years": 15
    },
    {
        "resume_id": 52,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 5
    },
    {
        "resume_id": 53,
        "skills": [
            "tableau",
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 18
    },
    {
        "resume_id": 54,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 5
    },
    {
        "resume_id": 55,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 56,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 10
    },
    {
        "resume_id": 57,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 5
    },
    {
        "resume_id": 58,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 59,
        "skills": [
            "Not Mentioned"
        ],
        "education": [],
        "experience_years": 15
    },
    {
        "resume_id": 60,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "mca"
        ],
        "experience_years": 6
    },
    {
        "resume_id": 61,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 62,
        "skills": [
            "excel"
        ],
        "education": [
            "computer science",
            "bachelor",
            "mba",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 63,
        "skills": [
            "Not Mentioned"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 64,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 6
    },
    {
        "resume_id": 65,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 66,
        "skills": [
            "data analysis",
            "excel"
        ],
        "education": [
            "bachelor",
            "mba",
            "master"
        ],
        "experience_years": 7
    },
    {
        "resume_id": 67,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 68,
        "skills": [
            "Not Mentioned"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 69,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "computer science"
        ],
        "experience_years": 15
    },
    {
        "resume_id": 70,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 12
    },
    {
        "resume_id": 71,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 20
    },
    {
        "resume_id": 72,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 20
    },
    {
        "resume_id": 73,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 74,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 10
    },
    {
        "resume_id": 75,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 76,
        "skills": [
            "excel"
        ],
        "education": [
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 77,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 78,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 79,
        "skills": [
            "sql",
            "java",
            "html",
            "excel",
            "javascript"
        ],
        "education": [
            "bachelor",
            "mba",
            "master"
        ],
        "experience_years": 4
    },
    {
        "resume_id": 80,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 81,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "mba"
        ],
        "experience_years": 5
    },
    {
        "resume_id": 82,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 6
    },
    {
        "resume_id": 83,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "information technology",
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 84,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 85,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 1
    },
    {
        "resume_id": 86,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 8
    },
    {
        "resume_id": 87,
        "skills": [
            "excel"
        ],
        "education": [
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 88,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "information technology"
        ],
        "experience_years": 6
    },
    {
        "resume_id": 89,
        "skills": [
            "excel"
        ],
        "education": [
            "mba"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 90,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "mba",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 91,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 92,
        "skills": [
            "sql",
            "java",
            "excel"
        ],
        "education": [
            "bachelor",
            "information technology",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 93,
        "skills": [
            "data analysis",
            "excel"
        ],
        "education": [
            "master"
        ],
        "experience_years": 10
    },
    {
        "resume_id": 94,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 95,
        "skills": [
            "excel"
        ],
        "education": [
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 96,
        "skills": [
            "Not Mentioned"
        ],
        "education": [],
        "experience_years": 5
    },
    {
        "resume_id": 97,
        "skills": [
            "excel"
        ],
        "education": [
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 98,
        "skills": [
            "data analysis",
            "excel"
        ],
        "education": [
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 99,
        "skills": [
            "excel"
        ],
        "education": [
            "bsc"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 100,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 101,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 27
    },
    {
        "resume_id": 102,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 5
    },
    {
        "resume_id": 103,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 8
    },
    {
        "resume_id": 104,
        "skills": [
            "excel"
        ],
        "education": [
            "bsc",
            "bachelor",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 105,
        "skills": [
            "excel"
        ],
        "education": [
            "bachelor",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 106,
        "skills": [
            "excel"
        ],
        "education": [],
        "experience_years": 0
    },
    {
        "resume_id": 107,
        "skills": [
            "excel"
        ],
        "education": [
            "mba",
            "master"
        ],
        "experience_years": 5
    },
    {
        "resume_id": 108,
        "skills": [
            "Not Mentioned"
        ],
        "education": [
            "mba",
            "master"
        ],
        "experience_years": 0
    },
    {
        "resume_id": 109,
        "skills": [
            "data analysis",
            "excel"
        ],
        "education": [
            "bachelor"
        ],
        "experience_years": 10
    },
    {
        "resume_id": 110,
        "skills": [
            "excel"
        ],
        "education": [

In [54]:
with open("parsed_resumes.json","w") as f:
    json.dump(resume_json,f,indent=4)

#Structured Resume Data in the Database

In [55]:
import sqlite3

In [56]:
conn = sqlite3.connect("resume_database.db")
cursor = conn.cursor()

In [57]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS resumes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    skills TEXT,
    education TEXT,
    experience INTEGER
)
""")

In [58]:
import json

for index,row in df.iterrows():

    skills = json.dumps(row['skills'])
    education = json.dumps(row['education'])
    experience = row['total_experience']

    cursor.execute("""
    INSERT INTO resumes (skills, education, experience)
    VALUES (?, ?, ?)
    """,(skills, education, experience))

In [59]:
conn.commit()

In [60]:
cursor.execute("SELECT * FROM resumes LIMIT 5")

rows = cursor.fetchall()

for r in rows:
    print(r)

(1, '["data analysis"]', '[]', 15)
(2, '["Not Mentioned"]', '["bachelor", "master"]', 0)
(3, '["excel"]', '["bachelor", "mba", "master"]', 20)
(4, '["excel"]', '[]', 20)
(5, '["excel"]', '["bachelor"]', 0)

In [61]:
conn.close()